apiVersion: 1

providers:
  - name: 'InfluxDB Datasource'
    orgId: 1
    folder: ''
    type: file
    disableDeletion: false
    options:
      path: /etc/grafana/provisioning/datasources

  - name: 'Market Data Dashboards'
    orgId: 1
    folder: 'Market Data'
    type: file
    disableDeletion: false
    options:
      path: /etc/grafana/provisioning/dashboards
