#!/bin/bash
#!/usr/bin/expect
set arg1 [lindex $argv 0];
set arg2 [lindex $argv 1];
set arg3 [lindex $argv 2];
set arg4 [lindex $argv 3];

log_user 0;
#set timeout 20
spawn "/home/sdreep/nabla/eurusdcount"
expect "How many times the word dollar appeared last *\r" {send "$arg1\r"}
expect "Enter current EURUSD price*\r" {send "$arg2\r"}
expect "How many times the word euro *\r" {send "$arg3\r"}
expect "What time *\r" {send "$arg4\r"}
#sleep 0.1
interact return -output $expect_out(buffer)
