apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: market_data_org
      defaultBucket: market_data
      tlsSkipVerify: false
    secureJsonData:
      token: market-data-token
    isDefault: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: market_data
    user: postgres
    secureJsonData:
      password: postgres
    isDefault: false
